---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-gh-autogov-policy-library
  description: Repo to host and publish OPA rego policies for attestations created by GitHub asset action.
  annotations:
    github.com/project-slug: ***REMOVED***/demo-gh-autogov-policy-library
  tags:
    - automated-governance
    - policy
    - rego
    - opa
spec:
  type: library
  lifecycle: experimental
  owner: tag-autogov
  system: demo-gh-attest-autogov
