version: '3.9'

x-variables:
  images:
    custom-opa: &image-custom-opa custom-opa:latest
  volumes:
    cwd: &vol-cwd
      type: bind
      source: ${PWD}
      target: /home

services:
  eval-good:
    build:
      context: .
      dockerfile: Dockerfile.opa
    image: *image-custom-opa
    volumes:
      - *vol-cwd
    command:
      [
        "sh",
        "-c",
        "opa eval --fail --input <(jq -s . home/test/sigstore_bundle_real.jsonl) -d home/policies/security/sbom.rego -d home/policies/security/provenance.rego -d home/policies/governance/governance.rego data.governance.violations; echo $? && opa eval --fail --input <(jq -s . home/test/sigstore_bundle_real.jsonl) -d home/policies/security/sbom.rego -d home/policies/security/provenance.rego -d home/policies/governance/governance.rego data.governance.allow; echo $?",
      ]
  eval-bad:
    build:
      context: .
      dockerfile: Dockerfile.opa
    image: *image-custom-opa
    volumes:
      - *vol-cwd
    command:
      [
        "sh",
        "-c",
        "opa eval --fail --input <(jq -s . home/test/sigstore_bundle_fake.jsonl) -d home/policies/security/sbom.rego -d home/policies/security/provenance.rego -d home/policies/governance/governance.rego data.governance.violations; echo $? && opa eval --fail --input <(jq -s . home/test/sigstore_bundle_fake.jsonl) -d home/policies/security/sbom.rego -d home/policies/security/provenance.rego -d home/policies/governance/governance.rego data.governance.allow; echo $?",
      ]
  fmt:
    build:
      context: .
      dockerfile: Dockerfile.opa
    image: *image-custom-opa
    volumes:
      - *vol-cwd
    command: ["opa", "fmt", "--write", "/home"]
  lint:
    build:
      context: .
      dockerfile: Dockerfile.opa
    image: *image-custom-opa
    volumes:
      - *vol-cwd
    command: ["regal", "lint", "/home"]
  check:
    build:
      context: .
      dockerfile: Dockerfile.opa
    image: *image-custom-opa
    volumes:
      - *vol-cwd
    command: ["opa", "check", "/home"]
  test:
    build:
      context: .
      dockerfile: Dockerfile.opa
    image: *image-custom-opa
    volumes:
      - *vol-cwd
    command: ["opa", "test", "/home"]