on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'catalog-info.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 #v2.2.0
        with:
          version: 0.67.1
      - name: Run OPA Tests
        id: run-opa-tests
        run: opa test policy -v

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 #v2.2.0
      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
      - name: Run OPA Tests
        run: opa test policy -v
      - name: Build OPA Bundle
        run: |
          opa build --ignore "*_test.rego" policy
      - name: Setup Semantic Release
        run: npm install -g semantic-release @semantic-release/github -D
      - name: Release OPA Bundle
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ github.token }}